### ISSUE TITLE
Trying to run aurorium with getting started guide only provides errors? 

### ISSUE THREAD

**Issue by ProfElements** [Revive101/Aurorium#6]
When running aurorium via `cargo run` its errors. 

```
    Running `target/debug/aurorium`
[2023-10-20T06:13:20Z ERROR aurorium] There are no revisions for the server to host! (Quitting)
```

When running aurorium via `cargo run -- -r V_r740872.Wizard_1_520` its errors. 

```
     Running `target/debug/aurorium -r 'V_r740872.Wizard_1_520`'`
[1/6] 🔍  Resolving revision...
[2/6] 🚚  Fetching LatestFileList...
thread 'main' panicked at src/http/http_request.rs:112:22:
Could not parse JSON: Error("missing field `LatestFileList`", line: 1, column: 620)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is there something i am not getting to run this?

**Comment by Phill030** [comment]
Hello 👋🏻
firstly, thanks for using Aurorium. Since the Wizard101 Launcher uses some unknown method to retrieve the latest revision, you need to start the launcher first and login. When you've done that, you can open the explorer at `your\path\to\Wizard101\Bin` and open the revision.dat file, which contains the latest revision. The latest revision is `r743518.Wizard_1_520` & KingsIsle only hosts latest revision, which is why we have our own backend to host custom revisions.

**Comment by ProfElements** [comment]
Running with the latest version `r743518.Wizard_1_520` still gives me the same error. 
```
     Running `target/debug/aurorium -r r743518.Wizard_1_520`
[1/6] 🔍  Resolving revision...
[2/6] 🚚  Fetching LatestFileList...
thread 'main' panicked at src/http/http_request.rs:112:22:
Could not parse JSON: Error("missing field `LatestFileList`", line: 1, column: 620)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ProfElements** [comment]
I had to specify `V_(revision number)`  to get properly working
Thank you :0
